# .github/workflows/ci-cd.yml

name: CI/CD Pipeline for FastAPI

# Trigger pipeline when code is pushed to main or pull requests are opened
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run tests (Adjust according to your test framework)
      - name: Run tests
        run: |
          pytest  # Run unit tests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build FastAPI (this may vary depending on how you're building)
      - name: Build FastAPI application
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to Render (example)
      - name: Deploy to Render
        run: |
          # Use Render CLI or APIs to deploy (you'll need to configure API tokens)
          echo "Deploying to Render"
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Add API key as a GitHub secret
